fix bug with full paths in extract_test_log srcript

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -66,7 +66,7 @@ run-all:
 	              FILE=$$file; \
 	       fi; \
 	     fi \
-	  && echo " => passed" || echo " => failed"; \
+	  && echo " => passed" || echo " => *** FAILED ***"; \
 	done
 
 .PHONY: run-file
